-- Rewrites every challenge description on one template, so the same question always reads the same way.
--
-- The V47 copy mixed several phrasings for the same kind of objective: a sum over several matches
-- sometimes read like a single-match bar, the period was sometimes missing, and "compétitives" and
-- "parties en Compétitif" named the same mode. Every description now follows one shape:
--
--   * a sum over several matches starts with "Cumuler", or with "Jouer"/"Remporter" for a count;
--   * a bar held match after match reads "Terminer N parties ... avec au moins X ... par partie";
--   * the mode comes right after the figure, then the period: "dans la journée", "sur la semaine",
--     or "dans une même journée de la semaine" for a best-day objective.
--
-- ChallengeDescriptionResolver swaps the numbers in place for the campaign's grid and drops the plural
-- after a resolved 1, so a count that is 1 on one grid and 2 on the other is written in the plural.

UPDATE challenge SET description = 'Jouer 1 parties en Compétitif ou Non classé dans la journée.' WHERE code = 'DAILY_ONE_LONG';
UPDATE challenge SET description = 'Jouer 3 parties, tous modes confondus, dans la journée.' WHERE code = 'DAILY_TWO_MATCHES';
UPDATE challenge SET description = 'Jouer 20 rounds en Compétitif ou Non classé dans la journée.' WHERE code = 'DAILY_LONG_ROUNDS';
UPDATE challenge SET description = 'Cumuler 50 kills, tous modes confondus, dans la journée.' WHERE code = 'DAILY_DAY_KILLS';
UPDATE challenge SET description = 'Cumuler 20 kills en Compétitif ou Non classé dans la journée.' WHERE code = 'DAILY_LONG_KILLS_DAY';
UPDATE challenge SET description = 'Cumuler 40 kills en Deathmatch dans la journée.' WHERE code = 'DAILY_DM_KILLS_DAY';
UPDATE challenge SET description = 'Cumuler 20 kills en Skirmish 2v2 dans la journée.' WHERE code = 'DAILY_SKIRMISH_KILLS_DAY';
UPDATE challenge SET description = 'Cumuler 12 000 de score de combat, tous modes confondus, dans la journée.' WHERE code = 'DAILY_DAY_SCORE';
UPDATE challenge SET description = 'Terminer 2 parties en Compétitif ou Non classé dans la journée avec au moins 15 kills par partie.' WHERE code = 'DAILY_LONG_DOUBLE';
UPDATE challenge SET description = 'Terminer 1 partie en Compétitif ou Non classé dans la journée avec au moins 6 headshots.' WHERE code = 'DAILY_LONG_HEADSHOTS';
UPDATE challenge SET description = 'Cumuler 25 headshots, tous modes confondus, dans la journée.' WHERE code = 'DAILY_DAY_HEADSHOTS';
UPDATE challenge SET description = 'Cumuler 5 assists, tous modes confondus, dans la journée.' WHERE code = 'DAILY_DAY_ASSISTS';
UPDATE challenge SET description = 'Cumuler 5 000 dégâts, tous modes confondus, dans la journée.' WHERE code = 'DAILY_DAY_DAMAGE';
UPDATE challenge SET description = 'Cumuler 3 000 dégâts en Compétitif ou Non classé dans la journée.' WHERE code = 'DAILY_LONG_DAMAGE';
UPDATE challenge SET description = 'Cumuler 4 000 dégâts en Team Deathmatch dans la journée.' WHERE code = 'DAILY_TDM_DAMAGE';
UPDATE challenge SET description = 'Jouer 2 parties en Deathmatch dans la journée.' WHERE code = 'DAILY_DM_ROUTINE';
UPDATE challenge SET description = 'Jouer 2 parties en Skirmish 2v2 dans la journée.' WHERE code = 'DAILY_SKIRMISH_ROUTINE';
UPDATE challenge SET description = 'Terminer 1 partie en Deathmatch dans la journée avec au moins 20 kills.' WHERE code = 'DAILY_DM_KILLS';
UPDATE challenge SET description = 'Terminer 2 parties en Deathmatch dans la journée avec au moins 15 kills par partie.' WHERE code = 'DAILY_DM_DOUBLE';
UPDATE challenge SET description = 'Terminer 1 partie en Team Deathmatch dans la journée avec au moins 25 kills.' WHERE code = 'DAILY_TDM_KILLS';
UPDATE challenge SET description = 'Remporter 1 parties en Compétitif ou Non classé dans la journée.' WHERE code = 'DAILY_LONG_WIN';
UPDATE challenge SET description = 'Remporter 2 parties, tous modes confondus, dans la journée.' WHERE code = 'DAILY_TWO_WINS';
UPDATE challenge SET description = 'Remporter 1 parties en Team Deathmatch dans la journée.' WHERE code = 'DAILY_TDM_WIN';
UPDATE challenge SET description = 'Remporter 1 parties en Skirmish 2v2 dans la journée.' WHERE code = 'DAILY_SKIRMISH_WIN';
UPDATE challenge SET description = 'Remporter au moins une partie dans 2 modes différents dans la journée.' WHERE code = 'DAILY_MODE_WINS';
UPDATE challenge SET description = 'Jouer au moins une partie avec 2 agents différents, tous modes confondus, dans la journée.' WHERE code = 'DAILY_AGENT_VARIETY';
UPDATE challenge SET description = 'Remporter au moins une partie avec 2 agents différents, tous modes confondus, dans la journée.' WHERE code = 'DAILY_AGENT_WINS';
UPDATE challenge SET description = 'Jouer au moins une partie dans 3 modes différents dans la journée.' WHERE code = 'DAILY_TWO_MODES';
UPDATE challenge SET description = 'Jouer 3 parties en Compétitif ou Non classé sur la semaine.' WHERE code = 'EASY_LONG_MATCHES';
UPDATE challenge SET description = 'Jouer 15 parties, tous modes confondus, sur la semaine.' WHERE code = 'EASY_ANY_MATCHES';
UPDATE challenge SET description = 'Jouer 60 rounds en Compétitif ou Non classé sur la semaine.' WHERE code = 'EASY_LONG_ROUNDS';
UPDATE challenge SET description = 'Cumuler 100 kills en Compétitif ou Non classé sur la semaine.' WHERE code = 'EASY_LONG_KILLS';
UPDATE challenge SET description = 'Cumuler 25 000 de score de combat en Compétitif ou Non classé sur la semaine.' WHERE code = 'EASY_LONG_SCORE';
UPDATE challenge SET description = 'Terminer 3 parties en Compétitif ou Non classé sur la semaine avec au moins 13 kills par partie.' WHERE code = 'EASY_LONG_KILL_GAMES';
UPDATE challenge SET description = 'Cumuler 40 headshots en Compétitif ou Non classé sur la semaine.' WHERE code = 'EASY_LONG_HEADSHOTS';
UPDATE challenge SET description = 'Terminer 3 parties en Compétitif ou Non classé sur la semaine avec au moins 8 headshots par partie.' WHERE code = 'EASY_LONG_HS_GAMES';
UPDATE challenge SET description = 'Cumuler 40 kills en Skirmish 2v2 sur la semaine.' WHERE code = 'EASY_SKIRMISH_KILLS';
UPDATE challenge SET description = 'Cumuler 30 assists en Compétitif ou Non classé sur la semaine.' WHERE code = 'EASY_LONG_ASSISTS';
UPDATE challenge SET description = 'Cumuler 13 000 dégâts en Compétitif ou Non classé sur la semaine.' WHERE code = 'EASY_LONG_DAMAGE';
UPDATE challenge SET description = 'Jouer 7 parties en Deathmatch sur la semaine.' WHERE code = 'EASY_DM_ROUTINE';
UPDATE challenge SET description = 'Jouer 3 parties en Team Deathmatch sur la semaine.' WHERE code = 'EASY_TDM_ROUTINE';
UPDATE challenge SET description = 'Cumuler 150 kills en Deathmatch sur la semaine.' WHERE code = 'EASY_DM_KILLS';
UPDATE challenge SET description = 'Remporter 2 parties en Compétitif ou Non classé sur la semaine.' WHERE code = 'EASY_LONG_WINS';
UPDATE challenge SET description = 'Remporter 2 parties en Team Deathmatch sur la semaine.' WHERE code = 'EASY_TDM_WINS';
UPDATE challenge SET description = 'Jouer au moins une partie, tous modes confondus, sur 3 jours différents de la semaine.' WHERE code = 'EASY_PLAY_DAYS';
UPDATE challenge SET description = 'Terminer 3 parties en Compétitif ou Non classé sur la semaine avec un K/D d''au moins 1,00 par partie.' WHERE code = 'EASY_LONG_KD_GAMES';
UPDATE challenge SET description = 'Jouer au moins une partie avec 2 agents différents en Compétitif ou Non classé sur la semaine.' WHERE code = 'EASY_AGENT_VARIETY';
UPDATE challenge SET description = 'Cumuler 60 kills, tous modes confondus, dans une même journée de la semaine.' WHERE code = 'EASY_DAY_BEST_KILLS';
UPDATE challenge SET description = 'Jouer 4 parties en Compétitif ou Non classé sur la semaine.' WHERE code = 'NORMAL_LONG_MATCHES';
UPDATE challenge SET description = 'Jouer 18 parties, tous modes confondus, sur la semaine.' WHERE code = 'NORMAL_ANY_MATCHES';
UPDATE challenge SET description = 'Jouer 75 rounds en Compétitif ou Non classé sur la semaine.' WHERE code = 'NORMAL_LONG_ROUNDS';
UPDATE challenge SET description = 'Cumuler 125 kills en Compétitif ou Non classé sur la semaine.' WHERE code = 'NORMAL_LONG_KILLS';
UPDATE challenge SET description = 'Cumuler 30 000 de score de combat en Compétitif ou Non classé sur la semaine.' WHERE code = 'NORMAL_LONG_SCORE';
UPDATE challenge SET description = 'Terminer 4 parties en Compétitif ou Non classé sur la semaine avec au moins 14 kills par partie.' WHERE code = 'NORMAL_LONG_KILL_GAMES';
UPDATE challenge SET description = 'Cumuler 50 headshots en Compétitif ou Non classé sur la semaine.' WHERE code = 'NORMAL_LONG_HEADSHOTS';
UPDATE challenge SET description = 'Terminer 4 parties en Compétitif ou Non classé sur la semaine avec au moins 10 headshots par partie.' WHERE code = 'NORMAL_LONG_HS_GAMES';
UPDATE challenge SET description = 'Cumuler 38 assists en Compétitif ou Non classé sur la semaine.' WHERE code = 'NORMAL_LONG_ASSISTS';
UPDATE challenge SET description = 'Cumuler 16 000 dégâts en Compétitif ou Non classé sur la semaine.' WHERE code = 'NORMAL_LONG_DAMAGE';
UPDATE challenge SET description = 'Terminer 4 parties en Compétitif ou Non classé sur la semaine avec au moins 130 d''ADR par partie.' WHERE code = 'NORMAL_LONG_ADR_GAMES';
UPDATE challenge SET description = 'Cumuler 190 kills en Deathmatch sur la semaine.' WHERE code = 'NORMAL_DM_KILLS';
UPDATE challenge SET description = 'Cumuler 120 kills en Team Deathmatch sur la semaine.' WHERE code = 'NORMAL_TDM_KILLS';
UPDATE challenge SET description = 'Terminer 6 parties en Deathmatch sur la semaine avec au moins 20 kills par partie.' WHERE code = 'NORMAL_DM_KILL_GAMES';
UPDATE challenge SET description = 'Remporter 3 parties en Compétitif ou Non classé sur la semaine.' WHERE code = 'NORMAL_LONG_WINS';
UPDATE challenge SET description = 'Remporter 3 parties, tous modes confondus, dans une même journée de la semaine.' WHERE code = 'NORMAL_DAY_WINS';
UPDATE challenge SET description = 'Jouer au moins une partie, tous modes confondus, sur 4 jours différents de la semaine.' WHERE code = 'NORMAL_PLAY_DAYS';
UPDATE challenge SET description = 'Terminer 4 parties en Compétitif ou Non classé sur la semaine avec un K/D d''au moins 1,05 par partie.' WHERE code = 'NORMAL_LONG_KD_GAMES';
UPDATE challenge SET description = 'Jouer au moins une partie dans 4 modes différents sur la semaine.' WHERE code = 'NORMAL_MODE_VARIETY';
UPDATE challenge SET description = 'Cumuler 75 kills, tous modes confondus, dans une même journée de la semaine.' WHERE code = 'NORMAL_DAY_BEST_KILLS';
UPDATE challenge SET description = 'Jouer 5 parties en Compétitif ou Non classé sur la semaine.' WHERE code = 'MEDIUM_LONG_MATCHES';
UPDATE challenge SET description = 'Jouer 22 parties, tous modes confondus, sur la semaine.' WHERE code = 'MEDIUM_ANY_MATCHES';
UPDATE challenge SET description = 'Jouer 95 rounds en Compétitif ou Non classé sur la semaine.' WHERE code = 'MEDIUM_LONG_ROUNDS';
UPDATE challenge SET description = 'Cumuler 155 kills en Compétitif ou Non classé sur la semaine.' WHERE code = 'MEDIUM_LONG_KILLS';
UPDATE challenge SET description = 'Cumuler 38 000 de score de combat en Compétitif ou Non classé sur la semaine.' WHERE code = 'MEDIUM_LONG_SCORE';
UPDATE challenge SET description = 'Terminer 5 parties en Compétitif ou Non classé sur la semaine avec au moins 15 kills par partie.' WHERE code = 'MEDIUM_LONG_KILL_GAMES';
UPDATE challenge SET description = 'Terminer 5 parties en Compétitif ou Non classé sur la semaine avec au moins 225 d''ACS par partie.' WHERE code = 'MEDIUM_LONG_ACS_GAMES';
UPDATE challenge SET description = 'Terminer 5 parties en Compétitif ou Non classé sur la semaine avec au moins 11 headshots par partie.' WHERE code = 'MEDIUM_LONG_HS_GAMES';
UPDATE challenge SET description = 'Cumuler 65 headshots en Compétitif ou Non classé sur la semaine.' WHERE code = 'MEDIUM_LONG_HEADSHOTS';
UPDATE challenge SET description = 'Cumuler 48 assists en Compétitif ou Non classé sur la semaine.' WHERE code = 'MEDIUM_LONG_ASSISTS';
UPDATE challenge SET description = 'Cumuler 20 000 dégâts en Compétitif ou Non classé sur la semaine.' WHERE code = 'MEDIUM_LONG_DAMAGE';
UPDATE challenge SET description = 'Terminer 5 parties en Compétitif ou Non classé sur la semaine avec au moins 135 d''ADR par partie.' WHERE code = 'MEDIUM_LONG_ADR_GAMES';
UPDATE challenge SET description = 'Jouer 11 parties en Deathmatch sur la semaine.' WHERE code = 'MEDIUM_DM_MATCHES';
UPDATE challenge SET description = 'Cumuler 100 kills en Skirmish 2v2 sur la semaine.' WHERE code = 'MEDIUM_SKIRMISH_KILLS';
UPDATE challenge SET description = 'Cumuler 95 kills, tous modes confondus, dans une même journée de la semaine.' WHERE code = 'MEDIUM_DAY_BEST_KILLS';
UPDATE challenge SET description = 'Remporter 3 parties en Team Deathmatch sur la semaine.' WHERE code = 'MEDIUM_TDM_WINS';
UPDATE challenge SET description = 'Remporter au moins une partie en Compétitif ou Non classé sur 2 jours différents de la semaine.' WHERE code = 'MEDIUM_WIN_DAYS';
UPDATE challenge SET description = 'Jouer au moins une partie, tous modes confondus, sur 5 jours différents de la semaine.' WHERE code = 'MEDIUM_PLAY_DAYS';
UPDATE challenge SET description = 'Terminer 5 parties en Compétitif ou Non classé sur la semaine avec un K/D d''au moins 1,10 par partie.' WHERE code = 'MEDIUM_LONG_KD_GAMES';
UPDATE challenge SET description = 'Remporter au moins une partie avec 3 agents différents en Compétitif ou Non classé sur la semaine.' WHERE code = 'MEDIUM_AGENT_WINS';
UPDATE challenge SET description = 'Jouer 28 parties, tous modes confondus, sur la semaine.' WHERE code = 'HARD_ANY_MATCHES';
UPDATE challenge SET description = 'Jouer 145 rounds en Compétitif ou Non classé sur la semaine.' WHERE code = 'HARD_LONG_ROUNDS';
UPDATE challenge SET description = 'Jouer 9 parties en Compétitif ou Non classé sur la semaine.' WHERE code = 'HARD_LONG_MATCHES';
UPDATE challenge SET description = 'Cumuler 195 kills en Compétitif ou Non classé sur la semaine.' WHERE code = 'HARD_LONG_KILLS';
UPDATE challenge SET description = 'Cumuler 48 000 de score de combat en Compétitif ou Non classé sur la semaine.' WHERE code = 'HARD_LONG_SCORE';
UPDATE challenge SET description = 'Terminer 6 parties en Compétitif ou Non classé sur la semaine avec au moins 16 kills par partie.' WHERE code = 'HARD_LONG_KILL_GAMES';
UPDATE challenge SET description = 'Terminer 6 parties en Compétitif ou Non classé sur la semaine avec au moins 250 d''ACS par partie.' WHERE code = 'HARD_LONG_ACS_GAMES';
UPDATE challenge SET description = 'Cumuler 115 kills, tous modes confondus, dans une même journée de la semaine.' WHERE code = 'HARD_DAY_BEST_KILLS';
UPDATE challenge SET description = 'Cumuler 80 headshots en Compétitif ou Non classé sur la semaine.' WHERE code = 'HARD_LONG_HEADSHOTS';
UPDATE challenge SET description = 'Terminer 6 parties en Compétitif ou Non classé sur la semaine avec au moins 12 headshots par partie.' WHERE code = 'HARD_LONG_HS_GAMES';
UPDATE challenge SET description = 'Cumuler 60 assists en Compétitif ou Non classé sur la semaine.' WHERE code = 'HARD_LONG_ASSISTS';
UPDATE challenge SET description = 'Cumuler 25 000 dégâts en Compétitif ou Non classé sur la semaine.' WHERE code = 'HARD_LONG_DAMAGE';
UPDATE challenge SET description = 'Terminer 6 parties en Compétitif ou Non classé sur la semaine avec au moins 140 d''ADR par partie.' WHERE code = 'HARD_LONG_ADR_GAMES';
UPDATE challenge SET description = 'Terminer 10 parties en Deathmatch sur la semaine avec au moins 25 kills par partie.' WHERE code = 'HARD_DM_KILL_GAMES';
UPDATE challenge SET description = 'Terminer 3 parties en Team Deathmatch sur la semaine avec au moins 28 kills par partie.' WHERE code = 'HARD_TDM_KILL_GAMES';
UPDATE challenge SET description = 'Remporter 5 parties en Compétitif ou Non classé sur la semaine.' WHERE code = 'HARD_LONG_WINS';
UPDATE challenge SET description = 'Remporter au moins une partie en Compétitif ou Non classé sur 3 jours différents de la semaine.' WHERE code = 'HARD_WIN_DAYS';
UPDATE challenge SET description = 'Jouer au moins une partie, tous modes confondus, sur 6 jours différents de la semaine.' WHERE code = 'HARD_DAILY_PLAYER';
UPDATE challenge SET description = 'Terminer 6 parties en Compétitif ou Non classé sur la semaine avec un K/D d''au moins 1,15 par partie.' WHERE code = 'HARD_LONG_KD_GAMES';
UPDATE challenge SET description = 'Jouer au moins une partie dans 5 modes différents sur la semaine.' WHERE code = 'HARD_MODE_VARIETY';
UPDATE challenge SET description = 'Jouer 180 rounds en Compétitif sur la semaine.' WHERE code = 'VERY_HARD_COMP_ROUNDS';
UPDATE challenge SET description = 'Jouer 4 parties en Compétitif dans une même journée de la semaine.' WHERE code = 'VERY_HARD_DAY_COMP_MATCHES';
UPDATE challenge SET description = 'Cumuler 245 kills en Compétitif sur la semaine.' WHERE code = 'VERY_HARD_COMP_KILLS';
UPDATE challenge SET description = 'Cumuler 60 000 de score de combat en Compétitif sur la semaine.' WHERE code = 'VERY_HARD_COMP_SCORE';
UPDATE challenge SET description = 'Terminer 7 parties en Compétitif sur la semaine avec au moins 17 kills par partie.' WHERE code = 'VERY_HARD_COMP_KILL_GAMES';
UPDATE challenge SET description = 'Terminer 7 parties en Compétitif sur la semaine avec au moins 275 d''ACS par partie.' WHERE code = 'VERY_HARD_COMP_ACS_GAMES';
UPDATE challenge SET description = 'Terminer 7 parties en Compétitif sur la semaine avec un K/D d''au moins 1,20 par partie.' WHERE code = 'VERY_HARD_COMP_KD_GAMES';
UPDATE challenge SET description = 'Cumuler 60 kills en Compétitif dans une même journée de la semaine.' WHERE code = 'VERY_HARD_DAY_BEST_KILLS';
UPDATE challenge SET description = 'Cumuler 100 headshots en Compétitif sur la semaine.' WHERE code = 'VERY_HARD_COMP_HEADSHOTS';
UPDATE challenge SET description = 'Terminer 7 parties en Compétitif sur la semaine avec au moins 13 headshots par partie.' WHERE code = 'VERY_HARD_COMP_HS_GAMES';
UPDATE challenge SET description = 'Cumuler 75 assists en Compétitif sur la semaine.' WHERE code = 'VERY_HARD_COMP_ASSISTS';
UPDATE challenge SET description = 'Cumuler 31 000 dégâts en Compétitif sur la semaine.' WHERE code = 'VERY_HARD_COMP_DAMAGE';
UPDATE challenge SET description = 'Terminer 7 parties en Compétitif sur la semaine avec au moins 145 d''ADR par partie.' WHERE code = 'VERY_HARD_COMP_ADR_GAMES';
UPDATE challenge SET description = 'Remporter 7 parties en Compétitif sur la semaine.' WHERE code = 'VERY_HARD_COMP_WINS';
UPDATE challenge SET description = 'Remporter au moins une partie en Compétitif sur 4 jours différents de la semaine.' WHERE code = 'VERY_HARD_CONSISTENCY';
UPDATE challenge SET description = 'Remporter 3 parties en Compétitif dans une même journée de la semaine.' WHERE code = 'VERY_HARD_DAY_COMP_WINS';
UPDATE challenge SET description = 'Jouer au moins une partie en Compétitif sur 6 jours différents de la semaine.' WHERE code = 'VERY_HARD_COMP_DAILY';
UPDATE challenge SET description = 'Terminer 5 parties en Compétitif sur la semaine avec au moins 5 000 de score de combat par partie.' WHERE code = 'VERY_HARD_COMP_SCORE_GAMES';
UPDATE challenge SET description = 'Cumuler 500 kills en Deathmatch sur la semaine.' WHERE code = 'VERY_HARD_DM_KILLS';
UPDATE challenge SET description = 'Terminer 12 parties en Deathmatch sur la semaine avec au moins 28 kills par partie.' WHERE code = 'VERY_HARD_DM_KILL_GAMES';
